
import { DailyQuoteData, Language } from './types';

export const THEMES = {
  stone: 'bg-stone-50 text-stone-900',
  slate: 'bg-slate-50 text-slate-900',
  rose: 'bg-rose-50 text-rose-900',
  amber: 'bg-amber-50 text-amber-900',
};

export const ACCENT_COLORS = {
  stone: 'text-stone-600 bg-stone-200 hover:bg-stone-300',
  slate: 'text-slate-600 bg-slate-200 hover:bg-slate-300',
  rose: 'text-rose-600 bg-rose-200 hover:bg-rose-300',
  amber: 'text-amber-800 bg-amber-200 hover:bg-amber-300',
};

export const BUTTON_STYLES = {
  stone: 'bg-stone-800 text-stone-50 hover:bg-stone-700',
  slate: 'bg-slate-800 text-slate-50 hover:bg-stone-700',
  rose: 'bg-rose-800 text-rose-50 hover:bg-stone-700',
  amber: 'bg-amber-800 text-amber-50 hover:bg-stone-700',
};

// Define English translations separately to reuse for other languages missing specific translations
const EN_TRANS = {
  appTitle: 'Life Notes',
  chatRooms: 'Chat Rooms',
  calendar: 'Calendar',
  createNote: 'Create Note',
  settings: 'Settings',
  history: "Buddha's Teachings",
  qna: 'Nikaya Knowledge',
  reminder: 'Reminders',
  calculator: 'Calculator',
  alarm: 'Alarm',
  worldClock: 'World Clock',
  stopwatch: 'Stopwatch',
  timer: 'Countdown',
  start: 'Start',
  stop: 'Stop',
  reset: 'Reset',
  close: 'Close',
  save: 'Save',
  download: 'Download',
  delete: 'Delete',
  cancel: 'Cancel',
  dailyQuote: 'Words of Wisdom',
  quoteExplanation: 'Reflection',
  source: 'Source',
  accessNikaya: 'Access Full Nikaya Library',
  loadingNikaya: 'Connecting to Nikaya Library...',
  welcome: 'Organize your mind, peaceful your soul',
  enterSite: 'Enter your private space name',
  go: 'Enter Space',
  title: 'Title',
  titlePlaceholder: 'Title...',
  font: 'Font',
  size: 'Size',
  color: 'Color',
  confirmDelete: 'Confirm Delete',
  password: 'Password',
  create: 'Create',
  unlock: 'Unlock',
  passwordRequired: 'Password required',
  enterPassword: 'Enter your password',
  wrongPassword: 'Wrong password',
  back: 'Back',
  search: 'Search',
  month: 'Month',
  week: 'Week',
  day: 'Day',
  schedule: 'Schedule',
  upcomingEvent: 'Upcoming Event',
  dismiss: 'Dismiss',
  snooze: 'Snooze',
  minutes: 'minutes',
  newNote: 'New Note',
  noNotes: 'No notes yet',
  eventSound: 'Event Sound',
  language: 'Language',
  theme: 'Theme',
  spaceName: 'Space Name',
  rename: 'Rename',
  optional: 'Optional',
  unlockSuccess: 'Unlocked successfully',
  unlockPrompt: 'Enter password to unlock',
  deleteSpaceConfirm: 'Delete this space? Content will be lost forever.',
  selectSpace: 'Select a space to begin',
  createSpace: 'Create New Space',
  today: 'Today',
  eventTitle: 'Event Title',
  allDay: 'All-day event',
  starts: 'Starts',
  ends: 'Ends',
  location: 'Location',
  description: 'Description',
  recurrence: 'Recurrence',
  none: 'None',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  yearly: 'Yearly',
  upload: 'Upload',
  volume: 'Volume',
  lunar: 'Lunar',
  allCalendars: 'All Calendars',
  localAccount: 'Local',
  googleAccount: 'Google',
  samsungAccount: 'Samsung',
  alarmSetting: 'Alarm Settings',
  repeats: 'Repeats',
  snoozeLabel: 'Snooze',
  custom: 'Custom',
  snoozeInputPlaceholder: 'Snooze minutes',
  snoozeInputHelp: 'Enter snooze duration',
  alarmName: 'Alarm Name',
  alarmNamePlaceholder: 'e.g. Work, Meds...',
  sound: 'Sound',
  yourMusic: 'Your Music',
  gradualVolume: 'Gradual Volume',
  timerName: 'Timer Name',
  timerPlaceholder: 'e.g. Cooking, Break...',
  timerPresets: 'Timer Presets',
  stopwatchHistory: 'Stopwatch History',
  noHistory: 'No history yet',
  laps: 'laps',
  searchCity: 'Search city...',
  deleteAlarmConfirm: 'Are you sure you want to delete this? This cannot be undone.',
  deleteNow: 'Delete Now',
  resume: 'Resume',
  lap: 'Lap',
  createNewSpaceTitle: 'Create New Space',
  spaceNamePlaceholder: 'Space Name...',
  passwordPlaceholder: 'Protection Password (Optional)...',
  createAction: 'Initialize',
  renameSpaceTitle: 'Rename Space',
  deleteSpaceTitle: 'Delete Space?',
  deleteSpaceMessage: 'Content will be deleted permanently.',
  passwordEmpty: 'Password cannot be empty',
  accessPrompt: 'Please enter password to access',
  unlockButton: 'Unlock',
  enterPasswordPlaceholder: 'Password...',
  selectSpacePrompt: 'Select a space to start',
  unsavedChangesTitle: 'Unsaved Changes',
  unsavedChangesMessage: 'You have unsaved changes. Do you want to save them before switching?',
  saveAndContinue: 'Save & Continue',
  discardAndContinue: 'Discard & Continue',
  sync: 'Sync',
  syncAccounts: 'Sync Accounts',
  contacts: 'Contacts',
  participants: 'Participants',
  syncSuccess: 'Synchronization complete',
  syncing: 'Syncing...',
  noContacts: 'No contacts found',
  addParticipant: 'Add Participant',
  addFromContacts: 'Pick from Contacts'
};

// Define Vietnamese translations separately
const VI_TRANS = {
  appTitle: 'Life Notes',
  chatRooms: 'Phòng Chat',
  calendar: 'Lịch',
  createNote: 'Ghi Chú',
  settings: 'Cài Đặt',
  history: 'Pháp Bảo',
  qna: 'Kiến Thức Nikaya',
  reminder: 'Nhắc Nhở',
  calculator: 'Máy Tính',
  alarm: 'Chuông báo',
  worldClock: 'Giờ quốc tế',
  stopwatch: 'Bấm giờ',
  timer: 'Đếm giờ ngược',
  start: 'Bắt đầu',
  stop: 'Dừng',
  reset: 'Đặt lại',
  dailyQuote: 'Lời Phật Dạy',
  close: 'Đóng',
  save: 'Lưu',
  download: 'Tải về',
  delete: 'Xóa',
  cancel: 'Hủy',
  quoteExplanation: 'Suy ngẫm',
  source: 'Nguồn',
  accessNikaya: 'Truy cập Thư viện Nikaya',
  loadingNikaya: 'Đang kết nối thư viện Nikaya...',
  welcome: 'Lắng đọng tâm hồn, an nhiên tự tại',
  enterSite: 'Nhập tên không gian riêng tư',
  go: 'Vào không gian',
  title: 'Tiêu đề',
  titlePlaceholder: 'Tiêu đề...',
  font: 'Phông chữ',
  size: 'Kích thước',
  color: 'Màu sắc',
  confirmDelete: 'Xác nhận xóa',
  password: 'Mật khẩu',
  create: 'Tạo mới',
  unlock: 'Mở khóa',
  passwordRequired: 'Yêu cầu mật khẩu',
  enterPassword: 'Nhập mật khẩu của bạn',
  wrongPassword: 'Mật khẩu không chính xác',
  back: 'Quay lại',
  search: 'Tìm kiếm',
  month: 'Tháng',
  week: 'Tuần',
  day: 'Ngày',
  schedule: 'Lịch trình',
  upcomingEvent: 'Sự kiện sắp tới',
  dismiss: 'Đóng',
  snooze: 'Báo lại',
  minutes: 'phút',
  newNote: 'Ghi chú mới',
  noNotes: 'Chưa có ghi chú nào',
  eventSound: 'Âm báo sự kiện',
  language: 'Ngôn ngữ',
  theme: 'Giao diện',
  spaceName: 'Tên không gian',
  rename: 'Đổi tên',
  optional: 'Tùy chọn',
  unlockSuccess: 'Mở khóa thành công',
  unlockPrompt: 'Vui lòng nhập mật mã để truy cập',
  deleteSpaceConfirm: 'Xóa không gian này? Nội dung sẽ bị xóa vĩnh viễn.',
  selectSpace: 'Chọn một không gian để bắt đầu',
  createSpace: 'Khởi tạo Không gian mới',
  today: 'Hôm nay',
  eventTitle: 'Tên sự kiện',
  allDay: 'Cả ngày',
  starts: 'Bắt đầu',
  ends: 'Kết thúc',
  location: 'Địa điểm',
  description: 'Mô tả',
  recurrence: 'Lặp lại',
  none: 'Không lặp',
  daily: 'Hàng ngày',
  weekly: 'Hàng tuần',
  monthly: 'Hàng tháng',
  yearly: 'Hàng năm',
  upload: 'Tải lên',
  volume: 'Âm lượng',
  lunar: 'Âm lịch',
  allCalendars: 'Tất cả lịch',
  localAccount: 'Cục bộ',
  googleAccount: 'Google',
  samsungAccount: 'Samsung',
  alarmSetting: 'Cài đặt báo thức',
  repeats: 'Lặp lại',
  snoozeLabel: 'Tạm hoãn (Snooze)',
  custom: 'Khác',
  snoozeInputPlaceholder: 'Số phút hoãn',
  snoozeInputHelp: 'Nhập số phút bạn muốn tạm hoãn',
  alarmName: 'Tên báo thức',
  alarmNamePlaceholder: 'Ví dụ: Đi làm, Uống thuốc...',
  sound: 'Âm báo',
  yourMusic: 'Nhạc của bạn',
  gradualVolume: 'Tăng dần âm lượng',
  timerName: 'Tên bộ đếm',
  timerPlaceholder: 'Ví dụ: Nấu mì, Nghỉ ngơi...',
  timerPresets: 'Bộ đếm mẫu',
  stopwatchHistory: 'Lịch sử bấm giờ',
  noHistory: 'Chưa có lịch sử',
  laps: 'vòng',
  searchCity: 'Tìm thành phố...',
  deleteAlarmConfirm: 'Bạn có chắc muốn xóa chuông báo này không? Thao tác này không thể hoàn tác.',
  deleteNow: 'Xóa ngay',
  resume: 'Tiếp tục',
  lap: 'Vòng',
  createNewSpaceTitle: 'Khởi tạo Không gian mới',
  spaceNamePlaceholder: 'Tên Không gian...',
  passwordPlaceholder: 'Mật mã bảo vệ (Tùy chọn)...',
  createAction: 'Khởi tạo',
  renameSpaceTitle: 'Đổi tên không gian',
  deleteSpaceTitle: 'Xóa không gian?',
  deleteSpaceMessage: 'Nội dung sẽ bị xóa vĩnh viễn.',
  passwordEmpty: 'Mật khẩu không được để trống',
  accessPrompt: 'Vui lòng nhập mật mã để truy cập',
  unlockButton: 'Mở khóa',
  enterPasswordPlaceholder: 'Mật mã...',
  selectSpacePrompt: 'Chọn một không gian để bắt đầu',
  unsavedChangesTitle: 'Thay đổi chưa lưu',
  unsavedChangesMessage: 'Bạn có thay đổi chưa được lưu. Bạn có muốn lưu lại trước khi tiếp tục không?',
  saveAndContinue: 'Lưu và Tiếp tục',
  discardAndContinue: 'Bỏ qua và Tiếp tục',
  sync: 'Đồng bộ',
  syncAccounts: 'Đồng bộ tài khoản',
  contacts: 'Danh bạ',
  participants: 'Người tham gia',
  syncSuccess: 'Đồng bộ hoàn tất',
  syncing: 'Đang đồng bộ...',
  noContacts: 'Không tìm thấy danh bạ',
  addParticipant: 'Thêm người tham gia',
  addFromContacts: 'Chọn từ danh bạ'
};

// Fix: Use all keys from Language union to satisfy Record<Language, ...>
export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: EN_TRANS,
  vi: VI_TRANS,
  fr: EN_TRANS,
  es: EN_TRANS,
  ru: EN_TRANS,
  zh: EN_TRANS,
  ko: EN_TRANS,
  ja: EN_TRANS,
  th: EN_TRANS,
  ar: EN_TRANS,
  hi: EN_TRANS,
};

export const QUOTES: DailyQuoteData[] = [
  {
    id: 1,
    imageUrl: "https://images.unsplash.com/photo-1528319725582-ddc096101511?auto=format&fit=crop&q=80&w=1000",
    content: {
      vi: {
        pali: "Manopubbaṅgamā dhammā, manoseṭṭhā manomayā.",
        vietnamese: "Ý dẫn đầu các pháp, Ý làm chủ, ý tạo.",
        explanation: "Mọi hành động và lời nói đều bắt nguồn từ tư duy. Nếu tâm ô nhiễm, khổ não sẽ theo sau như bánh xe theo chân con vật kéo.",
        source: "Kinh Pháp Cú (Dhammapada) - Kệ số 1"
      },
      en: {
        pali: "Manopubbaṅgamā dhammā, manoseṭṭhā manomayā.",
        vietnamese: "Mind precedes all mental states. Mind is their chief; they are all mind-wrought.",
        explanation: "All actions begin with thought. If one speaks or acts with an impure mind, suffering follows one like the wheel that follows the foot of the ox.",
        source: "Dhammapada - Verse 1"
      }
    }
  },
  {
    id: 2,
    imageUrl: "https://images.unsplash.com/photo-1507666405821-422402db4a73?auto=format&fit=crop&q=80&w=1000",
    content: {
      vi: {
        pali: "Na hi verena verāni, sammantīdha kudācanaṃ.",
        vietnamese: "Với hận diệt hận thù, đời này không có được.",
        explanation: "Lấy hận thù đáp lại hận thù chỉ làm nỗi đau thêm dài. Chỉ có lòng từ bi và sự bao dung mới có thể hóa giải mọi oán thù.",
        source: "Kinh Pháp Cú (Dhammapada) - Kệ số 5"
      },
      en: {
        pali: "Na hi verena verāni, sammantīdha kudācanaṃ.",
        vietnamese: "Hatred is never appeased by hatred in this world.",
        explanation: "Hatred is only appeased by love (non-hatred). This is an eternal law.",
        source: "Dhammapada - Verse 5"
      }
    }
  },
  {
    id: 3,
    imageUrl: "https://images.unsplash.com/photo-1464618663641-bbdd760ae84a?auto=format&fit=crop&q=80&w=1000",
    content: {
      vi: {
        pali: "Appamādo amatapadaṃ, pamādo maccuno padaṃ.",
        vietnamese: "Không phóng dật: đường sống, Phóng dật: đường đưa chết.",
        explanation: "Chánh niệm và tỉnh giác là con đường dẫn đến sự bất tử (Niết-bàn). Sự lơ là, buông lung là con đường dẫn đến sinh tử luân hồi.",
        source: "Kinh Pháp Cú (Dhammapada) - Kệ số 21"
      },
      en: {
        pali: "Appamādo amatapadaṃ, pamādo maccuno padaṃ.",
        vietnamese: "Heedfulness is the path to the deathless. Heedlessness is the path to death.",
        explanation: "The heedful die not. The heedless are as if dead already.",
        source: "Dhammapada - Verse 21"
      }
    }
  },
  {
    id: 4,
    imageUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=1000",
    content: {
      vi: {
        pali: "Yathāpi ruciraṃ pupphaṃ, vaṇṇavantaṃ agandhakaṃ.",
        vietnamese: "Như hoa đẹp có màu, Nhưng lại không có hương.",
        explanation: "Lời nói hay mà không thực hành thì cũng như hoa đẹp không hương, không mang lại lợi ích thực sự cho bản thân và người khác.",
        source: "Kinh Pháp Cú (Dhammapada) - Kệ số 51"
      },
      en: {
        pali: "Yathāpi ruciraṃ pupphaṃ, vaṇṇavantaṃ agandhakaṃ.",
        vietnamese: "Like a beautiful flower, full of color but without scent.",
        explanation: "Even so, fruitful is the well-spoken word of one who does not practice it.",
        source: "Dhammapada - Verse 51"
      }
    }
  }
];
